# Generated by Django 5.0.1 on 2024-02-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySleep',
            fields=[
                ('sleepId', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('userAddS', models.CharField(max_length=100)),
            ],
        ),
    ]
