# Generated by Django 5.0.6 on 2024-06-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDream',
            fields=[
                ('dreamId', models.AutoField(primary_key=True, serialize=False)),
                ('userNameAddS', models.CharField(max_length=100)),
                ('dreamDate', models.CharField(max_length=100)),
                ('dreamType', models.CharField(max_length=300)),
                ('dreamThing', models.CharField(max_length=900)),
            ],
        ),
    ]
